### ISSUE TITLE
Error: Disk object has no attribute 'Disk__hwmon_path'

### ISSUE THREAD

**Issue by ThreeTheOG** [petersulyok/diskinfo#4]
```
Traceback (most recent call last):
  File "/home/grimhex/Desktop/projects/sysstats_api/test.py", line 3, in <module>
    print(d.get_temperature())
          ^^^^^^^^^^^^^^^^^^^
  File "/home/grimhex/Desktop/projects/sysstats_api/lib/python3.11/site-packages/diskinfo/disk.py", line 554, in get_temperature
    if not self.__hwmon_path:
           ^^^^^^^^^^^^^^^^^
AttributeError: 'Disk' object has no attribute '_Disk__hwmon_path'. Did you mean: '_Disk__byid_path'?
```

Code Executed for this error:
```
from diskinfo import Disk
d = Disk("sdc")
print(d.get_temperature())
```
I tried using it in my project and not getting it to work, so I tried the docs version in a separate script and that didn't work. (/dev/sdc exists)

**Comment by petersulyok** [comment]
Hi @ThreeTheOG, I've got two ideas to explain this:
1.  In case of SATA drives you have to load `drivetemp` kernel module for temperature reading. This module will create the proper HWMON files in `/sys` filesystem.
2.  You may have SAS/SCSI drive and this is not supported by `drivetemp` module. In this case I'm planning to support `hddtemp` for temperature reading in a future release.

**Comment by ThreeTheOG** [comment]
Not loading the drivetemp driver was the issue, should have read the docs more carefully. Thanks for the quick response and the great work on this project.

**Comment by petersulyok** [comment]
I'm glad if it helps.
